//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badminton_Client.BadmintonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BadmintonService.DatabaseRESTSoap")]
    public interface DatabaseRESTSoap {
        
        // CODEGEN: Generating message contract since element name fornavn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        Badminton_Client.BadmintonService.AddUserResponse AddUser(Badminton_Client.BadmintonService.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddUserResponse> AddUserAsync(Badminton_Client.BadmintonService.AddUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(Badminton_Client.BadmintonService.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int medlemsId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fornavn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string efternavn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fodselsdato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string addresse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int postnr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tlf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string email;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(int medlemsId, string fornavn, string efternavn, string fodselsdato, string addresse, int postnr, string tlf, string email) {
            this.medlemsId = medlemsId;
            this.fornavn = fornavn;
            this.efternavn = efternavn;
            this.fodselsdato = fodselsdato;
            this.addresse = addresse;
            this.postnr = postnr;
            this.tlf = tlf;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(Badminton_Client.BadmintonService.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserResponseBody {
        
        public AddUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseRESTSoapChannel : Badminton_Client.BadmintonService.DatabaseRESTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseRESTSoapClient : System.ServiceModel.ClientBase<Badminton_Client.BadmintonService.DatabaseRESTSoap>, Badminton_Client.BadmintonService.DatabaseRESTSoap {
        
        public DatabaseRESTSoapClient() {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.AddUserResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.AddUser(Badminton_Client.BadmintonService.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public void AddUser(int medlemsId, string fornavn, string efternavn, string fodselsdato, string addresse, int postnr, string tlf, string email) {
            Badminton_Client.BadmintonService.AddUserRequest inValue = new Badminton_Client.BadmintonService.AddUserRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddUserRequestBody();
            inValue.Body.medlemsId = medlemsId;
            inValue.Body.fornavn = fornavn;
            inValue.Body.efternavn = efternavn;
            inValue.Body.fodselsdato = fodselsdato;
            inValue.Body.addresse = addresse;
            inValue.Body.postnr = postnr;
            inValue.Body.tlf = tlf;
            inValue.Body.email = email;
            Badminton_Client.BadmintonService.AddUserResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddUserResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.AddUserAsync(Badminton_Client.BadmintonService.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddUserResponse> AddUserAsync(int medlemsId, string fornavn, string efternavn, string fodselsdato, string addresse, int postnr, string tlf, string email) {
            Badminton_Client.BadmintonService.AddUserRequest inValue = new Badminton_Client.BadmintonService.AddUserRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddUserRequestBody();
            inValue.Body.medlemsId = medlemsId;
            inValue.Body.fornavn = fornavn;
            inValue.Body.efternavn = efternavn;
            inValue.Body.fodselsdato = fodselsdato;
            inValue.Body.addresse = addresse;
            inValue.Body.postnr = postnr;
            inValue.Body.tlf = tlf;
            inValue.Body.email = email;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddUserAsync(inValue);
        }
    }
}
