//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badminton_Client.BadmintonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BadmintonService.DatabaseRESTSoap")]
    public interface DatabaseRESTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignMemberToTeam", ReplyAction="*")]
        int AssignMemberToTeam(int memberId, int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignMemberToTeam", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AssignMemberToTeamAsync(int memberId, int teamId);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        Badminton_Client.BadmintonService.AddMemberResponse AddMember(Badminton_Client.BadmintonService.AddMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> AddMemberAsync(Badminton_Client.BadmintonService.AddMemberRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeam", ReplyAction="*")]
        Badminton_Client.BadmintonService.AddTeamResponse AddTeam(Badminton_Client.BadmintonService.AddTeamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeam", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddTeamResponse> AddTeamAsync(Badminton_Client.BadmintonService.AddTeamRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMemberAsInactive", ReplyAction="*")]
        Badminton_Client.BadmintonService.SetMemberAsInactiveResponse SetMemberAsInactive(Badminton_Client.BadmintonService.SetMemberAsInactiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMemberAsInactive", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.SetMemberAsInactiveResponse> SetMemberAsInactiveAsync(Badminton_Client.BadmintonService.SetMemberAsInactiveRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMemberActivity", ReplyAction="*")]
        Badminton_Client.BadmintonService.GetMemberActivityResponse GetMemberActivity(Badminton_Client.BadmintonService.GetMemberActivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMemberActivity", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.GetMemberActivityResponse> GetMemberActivityAsync(Badminton_Client.BadmintonService.GetMemberActivityRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginMember", ReplyAction="*")]
        Badminton_Client.BadmintonService.LoginMemberResponse LoginMember(Badminton_Client.BadmintonService.LoginMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginMember", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.LoginMemberResponse> LoginMemberAsync(Badminton_Client.BadmintonService.LoginMemberRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaveAdmin", ReplyAction="*")]
        Badminton_Client.BadmintonService.HaveAdminResponse HaveAdmin(Badminton_Client.BadmintonService.HaveAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HaveAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.HaveAdminResponse> HaveAdminAsync(Badminton_Client.BadmintonService.HaveAdminRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMember", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddMemberRequestBody Body;
        
        public AddMemberRequest() {
        }
        
        public AddMemberRequest(Badminton_Client.BadmintonService.AddMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mail;
        
        public AddMemberRequestBody() {
        }
        
        public AddMemberRequestBody(string firstName, string surName, string password, string cpr, string address, string zipCode, string phone, string mail) {
            this.firstName = firstName;
            this.surName = surName;
            this.password = password;
            this.cpr = cpr;
            this.address = address;
            this.zipCode = zipCode;
            this.phone = phone;
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddMemberResponseBody Body;
        
        public AddMemberResponse() {
        }
        
        public AddMemberResponse(Badminton_Client.BadmintonService.AddMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddMemberResult;
        
        public AddMemberResponseBody() {
        }
        
        public AddMemberResponseBody(int AddMemberResult) {
            this.AddMemberResult = AddMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeam", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddTeamRequestBody Body;
        
        public AddTeamRequest() {
        }
        
        public AddTeamRequest(Badminton_Client.BadmintonService.AddTeamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTeamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AddTeamRequestBody() {
        }
        
        public AddTeamRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeamResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddTeamResponseBody Body;
        
        public AddTeamResponse() {
        }
        
        public AddTeamResponse(Badminton_Client.BadmintonService.AddTeamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTeamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTeamResult;
        
        public AddTeamResponseBody() {
        }
        
        public AddTeamResponseBody(int AddTeamResult) {
            this.AddTeamResult = AddTeamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberAsInactiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMemberAsInactive", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.SetMemberAsInactiveRequestBody Body;
        
        public SetMemberAsInactiveRequest() {
        }
        
        public SetMemberAsInactiveRequest(Badminton_Client.BadmintonService.SetMemberAsInactiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMemberAsInactiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SetMemberAsInactiveRequestBody() {
        }
        
        public SetMemberAsInactiveRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMemberAsInactiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMemberAsInactiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.SetMemberAsInactiveResponseBody Body;
        
        public SetMemberAsInactiveResponse() {
        }
        
        public SetMemberAsInactiveResponse(Badminton_Client.BadmintonService.SetMemberAsInactiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMemberAsInactiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetMemberAsInactiveResult;
        
        public SetMemberAsInactiveResponseBody() {
        }
        
        public SetMemberAsInactiveResponseBody(int SetMemberAsInactiveResult) {
            this.SetMemberAsInactiveResult = SetMemberAsInactiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberActivityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberActivity", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.GetMemberActivityRequestBody Body;
        
        public GetMemberActivityRequest() {
        }
        
        public GetMemberActivityRequest(Badminton_Client.BadmintonService.GetMemberActivityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberActivityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetMemberActivityRequestBody() {
        }
        
        public GetMemberActivityRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMemberActivityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMemberActivityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.GetMemberActivityResponseBody Body;
        
        public GetMemberActivityResponse() {
        }
        
        public GetMemberActivityResponse(Badminton_Client.BadmintonService.GetMemberActivityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMemberActivityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetMemberActivityResult;
        
        public GetMemberActivityResponseBody() {
        }
        
        public GetMemberActivityResponseBody(int GetMemberActivityResult) {
            this.GetMemberActivityResult = GetMemberActivityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMember", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.LoginMemberRequestBody Body;
        
        public LoginMemberRequest() {
        }
        
        public LoginMemberRequest(Badminton_Client.BadmintonService.LoginMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginMemberRequestBody() {
        }
        
        public LoginMemberRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.LoginMemberResponseBody Body;
        
        public LoginMemberResponse() {
        }
        
        public LoginMemberResponse(Badminton_Client.BadmintonService.LoginMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginMemberResult;
        
        public LoginMemberResponseBody() {
        }
        
        public LoginMemberResponseBody(int LoginMemberResult) {
            this.LoginMemberResult = LoginMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaveAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaveAdmin", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.HaveAdminRequestBody Body;
        
        public HaveAdminRequest() {
        }
        
        public HaveAdminRequest(Badminton_Client.BadmintonService.HaveAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaveAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public HaveAdminRequestBody() {
        }
        
        public HaveAdminRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaveAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaveAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.HaveAdminResponseBody Body;
        
        public HaveAdminResponse() {
        }
        
        public HaveAdminResponse(Badminton_Client.BadmintonService.HaveAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HaveAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int HaveAdminResult;
        
        public HaveAdminResponseBody() {
        }
        
        public HaveAdminResponseBody(int HaveAdminResult) {
            this.HaveAdminResult = HaveAdminResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseRESTSoapChannel : Badminton_Client.BadmintonService.DatabaseRESTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseRESTSoapClient : System.ServiceModel.ClientBase<Badminton_Client.BadmintonService.DatabaseRESTSoap>, Badminton_Client.BadmintonService.DatabaseRESTSoap {
        
        public DatabaseRESTSoapClient() {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AssignMemberToTeam(int memberId, int teamId) {
            return base.Channel.AssignMemberToTeam(memberId, teamId);
        }
        
        public System.Threading.Tasks.Task<int> AssignMemberToTeamAsync(int memberId, int teamId) {
            return base.Channel.AssignMemberToTeamAsync(memberId, teamId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.AddMemberResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.AddMember(Badminton_Client.BadmintonService.AddMemberRequest request) {
            return base.Channel.AddMember(request);
        }
        
        public int AddMember(string firstName, string surName, string password, string cpr, string address, string zipCode, string phone, string mail) {
            Badminton_Client.BadmintonService.AddMemberRequest inValue = new Badminton_Client.BadmintonService.AddMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddMemberRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surName = surName;
            inValue.Body.password = password;
            inValue.Body.cpr = cpr;
            inValue.Body.address = address;
            inValue.Body.zipCode = zipCode;
            inValue.Body.phone = phone;
            inValue.Body.mail = mail;
            Badminton_Client.BadmintonService.AddMemberResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddMember(inValue);
            return retVal.Body.AddMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.AddMemberAsync(Badminton_Client.BadmintonService.AddMemberRequest request) {
            return base.Channel.AddMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> AddMemberAsync(string firstName, string surName, string password, string cpr, string address, string zipCode, string phone, string mail) {
            Badminton_Client.BadmintonService.AddMemberRequest inValue = new Badminton_Client.BadmintonService.AddMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddMemberRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surName = surName;
            inValue.Body.password = password;
            inValue.Body.cpr = cpr;
            inValue.Body.address = address;
            inValue.Body.zipCode = zipCode;
            inValue.Body.phone = phone;
            inValue.Body.mail = mail;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddMemberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.AddTeamResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.AddTeam(Badminton_Client.BadmintonService.AddTeamRequest request) {
            return base.Channel.AddTeam(request);
        }
        
        public int AddTeam(string name) {
            Badminton_Client.BadmintonService.AddTeamRequest inValue = new Badminton_Client.BadmintonService.AddTeamRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddTeamRequestBody();
            inValue.Body.name = name;
            Badminton_Client.BadmintonService.AddTeamResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddTeam(inValue);
            return retVal.Body.AddTeamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddTeamResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.AddTeamAsync(Badminton_Client.BadmintonService.AddTeamRequest request) {
            return base.Channel.AddTeamAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddTeamResponse> AddTeamAsync(string name) {
            Badminton_Client.BadmintonService.AddTeamRequest inValue = new Badminton_Client.BadmintonService.AddTeamRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddTeamRequestBody();
            inValue.Body.name = name;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddTeamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.SetMemberAsInactiveResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.SetMemberAsInactive(Badminton_Client.BadmintonService.SetMemberAsInactiveRequest request) {
            return base.Channel.SetMemberAsInactive(request);
        }
        
        public int SetMemberAsInactive(string email, string password) {
            Badminton_Client.BadmintonService.SetMemberAsInactiveRequest inValue = new Badminton_Client.BadmintonService.SetMemberAsInactiveRequest();
            inValue.Body = new Badminton_Client.BadmintonService.SetMemberAsInactiveRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Badminton_Client.BadmintonService.SetMemberAsInactiveResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).SetMemberAsInactive(inValue);
            return retVal.Body.SetMemberAsInactiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.SetMemberAsInactiveResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.SetMemberAsInactiveAsync(Badminton_Client.BadmintonService.SetMemberAsInactiveRequest request) {
            return base.Channel.SetMemberAsInactiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.SetMemberAsInactiveResponse> SetMemberAsInactiveAsync(string email, string password) {
            Badminton_Client.BadmintonService.SetMemberAsInactiveRequest inValue = new Badminton_Client.BadmintonService.SetMemberAsInactiveRequest();
            inValue.Body = new Badminton_Client.BadmintonService.SetMemberAsInactiveRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).SetMemberAsInactiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.GetMemberActivityResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.GetMemberActivity(Badminton_Client.BadmintonService.GetMemberActivityRequest request) {
            return base.Channel.GetMemberActivity(request);
        }
        
        public int GetMemberActivity(string email, string password) {
            Badminton_Client.BadmintonService.GetMemberActivityRequest inValue = new Badminton_Client.BadmintonService.GetMemberActivityRequest();
            inValue.Body = new Badminton_Client.BadmintonService.GetMemberActivityRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Badminton_Client.BadmintonService.GetMemberActivityResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).GetMemberActivity(inValue);
            return retVal.Body.GetMemberActivityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.GetMemberActivityResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.GetMemberActivityAsync(Badminton_Client.BadmintonService.GetMemberActivityRequest request) {
            return base.Channel.GetMemberActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.GetMemberActivityResponse> GetMemberActivityAsync(string email, string password) {
            Badminton_Client.BadmintonService.GetMemberActivityRequest inValue = new Badminton_Client.BadmintonService.GetMemberActivityRequest();
            inValue.Body = new Badminton_Client.BadmintonService.GetMemberActivityRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).GetMemberActivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.LoginMemberResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.LoginMember(Badminton_Client.BadmintonService.LoginMemberRequest request) {
            return base.Channel.LoginMember(request);
        }
        
        public int LoginMember(string email, string password) {
            Badminton_Client.BadmintonService.LoginMemberRequest inValue = new Badminton_Client.BadmintonService.LoginMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.LoginMemberRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Badminton_Client.BadmintonService.LoginMemberResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).LoginMember(inValue);
            return retVal.Body.LoginMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.LoginMemberResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.LoginMemberAsync(Badminton_Client.BadmintonService.LoginMemberRequest request) {
            return base.Channel.LoginMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.LoginMemberResponse> LoginMemberAsync(string email, string password) {
            Badminton_Client.BadmintonService.LoginMemberRequest inValue = new Badminton_Client.BadmintonService.LoginMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.LoginMemberRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).LoginMemberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.HaveAdminResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.HaveAdmin(Badminton_Client.BadmintonService.HaveAdminRequest request) {
            return base.Channel.HaveAdmin(request);
        }
        
        public int HaveAdmin(string email, string password) {
            Badminton_Client.BadmintonService.HaveAdminRequest inValue = new Badminton_Client.BadmintonService.HaveAdminRequest();
            inValue.Body = new Badminton_Client.BadmintonService.HaveAdminRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Badminton_Client.BadmintonService.HaveAdminResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).HaveAdmin(inValue);
            return retVal.Body.HaveAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.HaveAdminResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.HaveAdminAsync(Badminton_Client.BadmintonService.HaveAdminRequest request) {
            return base.Channel.HaveAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.HaveAdminResponse> HaveAdminAsync(string email, string password) {
            Badminton_Client.BadmintonService.HaveAdminRequest inValue = new Badminton_Client.BadmintonService.HaveAdminRequest();
            inValue.Body = new Badminton_Client.BadmintonService.HaveAdminRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).HaveAdminAsync(inValue);
        }
    }
}
