//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badminton_Client.BadmintonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BadmintonService.DatabaseRESTSoap")]
    public interface DatabaseRESTSoap {
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        Badminton_Client.BadmintonService.AddMemberResponse AddMember(Badminton_Client.BadmintonService.AddMemberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> AddMemberAsync(Badminton_Client.BadmintonService.AddMemberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMember", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddMemberRequestBody Body;
        
        public AddMemberRequest() {
        }
        
        public AddMemberRequest(Badminton_Client.BadmintonService.AddMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mail;
        
        public AddMemberRequestBody() {
        }
        
        public AddMemberRequestBody(string firstName, string surName, string cpr, string address, string zipCode, string phone, string mail) {
            this.firstName = firstName;
            this.surName = surName;
            this.cpr = cpr;
            this.address = address;
            this.zipCode = zipCode;
            this.phone = phone;
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public Badminton_Client.BadmintonService.AddMemberResponseBody Body;
        
        public AddMemberResponse() {
        }
        
        public AddMemberResponse(Badminton_Client.BadmintonService.AddMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddMemberResult;
        
        public AddMemberResponseBody() {
        }
        
        public AddMemberResponseBody(string AddMemberResult) {
            this.AddMemberResult = AddMemberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseRESTSoapChannel : Badminton_Client.BadmintonService.DatabaseRESTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseRESTSoapClient : System.ServiceModel.ClientBase<Badminton_Client.BadmintonService.DatabaseRESTSoap>, Badminton_Client.BadmintonService.DatabaseRESTSoap {
        
        public DatabaseRESTSoapClient() {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseRESTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Badminton_Client.BadmintonService.AddMemberResponse Badminton_Client.BadmintonService.DatabaseRESTSoap.AddMember(Badminton_Client.BadmintonService.AddMemberRequest request) {
            return base.Channel.AddMember(request);
        }
        
        public string AddMember(string firstName, string surName, string cpr, string address, string zipCode, string phone, string mail) {
            Badminton_Client.BadmintonService.AddMemberRequest inValue = new Badminton_Client.BadmintonService.AddMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddMemberRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surName = surName;
            inValue.Body.cpr = cpr;
            inValue.Body.address = address;
            inValue.Body.zipCode = zipCode;
            inValue.Body.phone = phone;
            inValue.Body.mail = mail;
            Badminton_Client.BadmintonService.AddMemberResponse retVal = ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddMember(inValue);
            return retVal.Body.AddMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> Badminton_Client.BadmintonService.DatabaseRESTSoap.AddMemberAsync(Badminton_Client.BadmintonService.AddMemberRequest request) {
            return base.Channel.AddMemberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Badminton_Client.BadmintonService.AddMemberResponse> AddMemberAsync(string firstName, string surName, string cpr, string address, string zipCode, string phone, string mail) {
            Badminton_Client.BadmintonService.AddMemberRequest inValue = new Badminton_Client.BadmintonService.AddMemberRequest();
            inValue.Body = new Badminton_Client.BadmintonService.AddMemberRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surName = surName;
            inValue.Body.cpr = cpr;
            inValue.Body.address = address;
            inValue.Body.zipCode = zipCode;
            inValue.Body.phone = phone;
            inValue.Body.mail = mail;
            return ((Badminton_Client.BadmintonService.DatabaseRESTSoap)(this)).AddMemberAsync(inValue);
        }
    }
}
